branches:
  only:
  - master
  - release
dist: trusty
language: python
python:
  - '3.5'
install: true
before_script:
  - git clone https://github.com/jokoho48/sqf.git sqfLint
  - pip install sqfLint
script:
  - python3 Tools/sqf_validator.py
  - python3 sqfLint/sqflint.py -d addons
  - python3 sqfLint/sqflint.py -d Missions
