branches:
  only:
  - master
  - release
dist: trusty
language: python
python:
  - '3.5'
install: true
before_script:
  - pip3 install sqflint
script:
  - python3 Tools/sqf_validator.py
  - sqflint -d addons
  - sqflint -d Missions
