version: 2
jobs:
  build:
    docker:
      - image: python:3-alpine
    steps:
      - checkout
      - run:
          name: Installing Requiremnts
          command: apt-get install git
      - run:
          name: Checkout sqfLint
          command: git clone https://github.com/jokoho48/sqf.git sqfLint
      - run:
          name: Validate SQF Addons
          command: python3 sqfLint/sqflint.py -d addons
      - run:
          name: Validate SQF Missions
          command: python3 sqfLint/sqflint.py -d Missions
