version: 2
jobs:
  build:
    docker:
      - image: python:3-alpine
    steps:
      - checkout
      - run:
        name: Validate SQF Addons and Mission
        command: python3 sqfLint/sqflint.py -d addons && python3 sqfLint/sqflint.py -d Missions
